### ISSUE TITLE
Error: No module named 'easymocap'

### ISSUE THREAD

**Issue by jamalknight** [carlosedubarreto/easymocap_win_install#1]
Hi Carlos

I get an error when running this command:

`python apps/demo/mv1p.py 0_input/sample --out 1_output/sample --vis_det --vis_repro --undis --sub_vis 1 7 13 19 --vis_smpl`

Error:

```
Traceback (most recent call last):
  File "apps/demo/mv1p.py", line 9, in <module>
    from easymocap.smplmodel import check_keypoints, load_model, select_nf
ModuleNotFoundError: No module named 'easymocap'
```

Did I miss something?

**Comment by carlosedubarreto** [comment]
Yep, looks like you are missing this part, that I forgot to mention on the tutorial (or that version didnt need that, I dont remember)

https://github.com/zju3dv/EasyMocap/blob/master/doc/installation.md#3-install

that link says that you should run this, at easymocap root folder:
`python3 setup.py develop --user`

or, in my case (in windows) you should run
`python setup.py develop --user`

**Comment by jamalknight** [comment]
Thanks Carlos, that worked

I ran:

`python3 setup.py develop --user`

But found that this worked instead (on windows)

`python setup.py develop --user`

Regards,
Jamal
